# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160212_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='show',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='show',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Day'),
        ),
    ]
